//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechFloor.Service.MYCRONIC.WebService.ReelTowerWebServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="RoyoTech.StSys", ConfigurationName="ReelTowerWebServiceReference.IWSInterface")]
    public interface IWSInterface {
        
        [System.ServiceModel.OperationContractAttribute(Action="RoyoTech.StSys/IWSInterface/WebServiceIsConnected", ReplyAction="RoyoTech.StSys/IWSInterface/WebServiceIsConnectedResponse")]
        bool WebServiceIsConnected();
        
        [System.ServiceModel.OperationContractAttribute(Action="RoyoTech.StSys/IWSInterface/WebServiceIsConnected", ReplyAction="RoyoTech.StSys/IWSInterface/WebServiceIsConnectedResponse")]
        System.Threading.Tasks.Task<bool> WebServiceIsConnectedAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="RoyoTech.StSys/IWSInterface/XmlAction", ReplyAction="RoyoTech.StSys/IWSInterface/XmlActionResponse")]
        System.Xml.Linq.XElement XmlAction(string xmlData);
        
        [System.ServiceModel.OperationContractAttribute(Action="RoyoTech.StSys/IWSInterface/XmlAction", ReplyAction="RoyoTech.StSys/IWSInterface/XmlActionResponse")]
        System.Threading.Tasks.Task<System.Xml.Linq.XElement> XmlActionAsync(string xmlData);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWSInterfaceChannel : TechFloor.Service.MYCRONIC.WebService.ReelTowerWebServiceReference.IWSInterface, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSInterfaceClient : System.ServiceModel.ClientBase<TechFloor.Service.MYCRONIC.WebService.ReelTowerWebServiceReference.IWSInterface>, TechFloor.Service.MYCRONIC.WebService.ReelTowerWebServiceReference.IWSInterface {
        
        public WSInterfaceClient() {
        }
        
        public WSInterfaceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WSInterfaceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSInterfaceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSInterfaceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool WebServiceIsConnected() {
            return base.Channel.WebServiceIsConnected();
        }
        
        public System.Threading.Tasks.Task<bool> WebServiceIsConnectedAsync() {
            return base.Channel.WebServiceIsConnectedAsync();
        }
        
        public System.Xml.Linq.XElement XmlAction(string xmlData) {
            return base.Channel.XmlAction(xmlData);
        }
        
        public System.Threading.Tasks.Task<System.Xml.Linq.XElement> XmlActionAsync(string xmlData) {
            return base.Channel.XmlActionAsync(xmlData);
        }
    }
}
