//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechFloor.Properties {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TechFloor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   (아이콘)과(와) 유사한 System.Drawing.Icon 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Icon ActionCenterCPL_2 {
            get {
                object obj = ResourceManager.GetObject("ActionCenterCPL_2", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   (아이콘)과(와) 유사한 System.Drawing.Icon 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Icon ActionCenterCPL_3 {
            get {
                object obj = ResourceManager.GetObject("ActionCenterCPL_3", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   (아이콘)과(와) 유사한 System.Drawing.Icon 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Icon ActionCenterCPL_4 {
            get {
                object obj = ResourceManager.GetObject("ActionCenterCPL_4", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   (아이콘)과(와) 유사한 System.Drawing.Icon 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Icon nvwss_9636 {
            get {
                object obj = ResourceManager.GetObject("nvwss_9636", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   (아이콘)과(와) 유사한 System.Drawing.Icon 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Icon nvwss_9637 {
            get {
                object obj = ResourceManager.GetObject("nvwss_9637", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   (아이콘)과(와) 유사한 System.Drawing.Icon 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Icon nvwss_9638 {
            get {
                object obj = ResourceManager.GetObject("nvwss_9638", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap robot_1 {
            get {
                object obj = ResourceManager.GetObject("robot_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap robot_1_black {
            get {
                object obj = ResourceManager.GetObject("robot_1_black", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap robot_1_blue {
            get {
                object obj = ResourceManager.GetObject("robot_1_blue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap robot_1_cyan {
            get {
                object obj = ResourceManager.GetObject("robot_1_cyan", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap robot_1_green {
            get {
                object obj = ResourceManager.GetObject("robot_1_green", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap robot_1_lime {
            get {
                object obj = ResourceManager.GetObject("robot_1_lime", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap robot_1_red {
            get {
                object obj = ResourceManager.GetObject("robot_1_red", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap robot_1_white {
            get {
                object obj = ResourceManager.GetObject("robot_1_white", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap robot_2_black {
            get {
                object obj = ResourceManager.GetObject("robot_2_black", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap robot_2_blue {
            get {
                object obj = ResourceManager.GetObject("robot_2_blue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap robot_2_green {
            get {
                object obj = ResourceManager.GetObject("robot_2_green", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap robot_2_red {
            get {
                object obj = ResourceManager.GetObject("robot_2_red", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap robot_2_white {
            get {
                object obj = ResourceManager.GetObject("robot_2_white", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap robot_2_yellow {
            get {
                object obj = ResourceManager.GetObject("robot_2_yellow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   ABORT과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string String_Abort {
            get {
                return ResourceManager.GetString("String_Abort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ASSIGN과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string String_Assign {
            get {
                return ResourceManager.GetString("String_Assign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   AUTO과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string String_Auto {
            get {
                return ResourceManager.GetString("String_Auto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   AUTO MODE과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string String_AutoMode {
            get {
                return ResourceManager.GetString("String_AutoMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OUTPUT STAGE 1과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string String_Button_OutputStage1 {
            get {
                return ResourceManager.GetString("String_Button_OutputStage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OUTPUT STAGE 2과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string String_Button_OutputStage2 {
            get {
                return ResourceManager.GetString("String_Button_OutputStage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OUTPUT STAGE 3과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string String_Button_OutputStage3 {
            get {
                return ResourceManager.GetString("String_Button_OutputStage3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CLEAN UP과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string String_CleanUp {
            get {
                return ResourceManager.GetString("String_CleanUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CLEAR과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string String_Clear {
            get {
                return ResourceManager.GetString("String_Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Completed과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string String_Completed {
            get {
                return ResourceManager.GetString("String_Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CREATE과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string String_Create {
            get {
                return ResourceManager.GetString("String_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ENQUEUE과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string String_Enqueue {
            get {
                return ResourceManager.GetString("String_Enqueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EXIT과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string String_Exit {
            get {
                return ResourceManager.GetString("String_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   APPLY과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string String_FormBarcodeInput_buttonApply {
            get {
                return ResourceManager.GetString("String_FormBarcodeInput_buttonApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   BUZZER OFF과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string String_FormBarcodeInput_buttonBuzzerOff {
            get {
                return ResourceManager.GetString("String_FormBarcodeInput_buttonBuzzerOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CLOSE과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string String_FormBarcodeInput_buttonClose {
            get {
                return ResourceManager.GetString("String_FormBarcodeInput_buttonClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please, type correct sid.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string String_FormBarcodeInput_Notification_Mistype_Sid {
            get {
                return ResourceManager.GetString("String_FormBarcodeInput_Notification_Mistype_Sid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please, type correct uid and sid.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string String_FormBarcodeInput_Notification_Mistype_Uid {
            get {
                return ResourceManager.GetString("String_FormBarcodeInput_Notification_Mistype_Uid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Check initialization state.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string String_FormInitialization_CheckInitializationState {
            get {
                return ResourceManager.GetString("String_FormInitialization_CheckInitializationState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Check notification listener.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string String_FormInitialization_CheckNotificationListener {
            get {
                return ResourceManager.GetString("String_FormInitialization_CheckNotificationListener", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Check reel handler.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string String_FormInitialization_CheckReelHandler {
            get {
                return ResourceManager.GetString("String_FormInitialization_CheckReelHandler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Check tower information.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string String_FormInitialization_CheckTtowerInformation {
            get {
                return ResourceManager.GetString("String_FormInitialization_CheckTtowerInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Complete initialization.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string String_FormInitialization_CompleteInitialization {
            get {
                return ResourceManager.GetString("String_FormInitialization_CompleteInitialization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed initialization.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string String_FormInitialization_FailedInitialization {
            get {
                return ResourceManager.GetString("String_FormInitialization_FailedInitialization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Initialize reel tower group.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string String_FormInitialization_InitializeReelTowerGroup {
            get {
                return ResourceManager.GetString("String_FormInitialization_InitializeReelTowerGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Initializing...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string String_FormInitialization_Initializing {
            get {
                return ResourceManager.GetString("String_FormInitialization_Initializing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Prepare initialization.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string String_FormInitialization_PrepareInitialization {
            get {
                return ResourceManager.GetString("String_FormInitialization_PrepareInitialization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reel tower group과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string String_FormInitialization_ReelTowerGroup {
            get {
                return ResourceManager.GetString("String_FormInitialization_ReelTowerGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ABORT과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string String_FormIntialization_buttonAbort {
            get {
                return ResourceManager.GetString("String_FormIntialization_buttonAbort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please, remove the reel ({0}) on tower ({1}).과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string String_FormLoadMaterialInformation_MessageAbort {
            get {
                return ResourceManager.GetString("String_FormLoadMaterialInformation_MessageAbort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A reel ({0}) is placed on tower ({1}) by robot.{2}Wait for reel tower operation!과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string String_FormLoadMaterialInformation_MessageAutoRun {
            get {
                return ResourceManager.GetString("String_FormLoadMaterialInformation_MessageAutoRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A reel ({0}) is placed on tower ({1}).{2}Would like to load ?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string String_FormLoadMaterialInformation_MessageManualRun {
            get {
                return ResourceManager.GetString("String_FormLoadMaterialInformation_MessageManualRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   LOAD MATERIAL INFORMATION과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string String_FormLoadReelInformation_labelTitle {
            get {
                return ResourceManager.GetString("String_FormLoadReelInformation_labelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   INITIALIZE과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string String_FormMain_buttonInitialize {
            get {
                return ResourceManager.GetString("String_FormMain_buttonInitialize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   RESET과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string String_FormMain_buttonReset {
            get {
                return ResourceManager.GetString("String_FormMain_buttonReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   START과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string String_FormMain_buttonStart {
            get {
                return ResourceManager.GetString("String_FormMain_buttonStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CYCLE STOP과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string String_FormMain_buttonStart_CycleStop {
            get {
                return ResourceManager.GetString("String_FormMain_buttonStart_CycleStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   STOP과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string String_FormMain_buttonStop {
            get {
                return ResourceManager.GetString("String_FormMain_buttonStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   RUN과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string String_FormMain_buttonVisionStart_Run {
            get {
                return ResourceManager.GetString("String_FormMain_buttonVisionStart_Run", resourceCulture);
            }
        }
        
        /// <summary>
        ///   STOPPED과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string String_FormMain_buttonVisionStart_Stopped {
            get {
                return ResourceManager.GetString("String_FormMain_buttonVisionStart_Stopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TF RUN과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string String_FormMain_buttonVisionStart_TF_Run {
            get {
                return ResourceManager.GetString("String_FormMain_buttonVisionStart_TF_Run", resourceCulture);
            }
        }
        
        /// <summary>
        ///   REEL 13&quot;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string String_FormMain_Cart_Reel_Type_13_Inch {
            get {
                return ResourceManager.GetString("String_FormMain_Cart_Reel_Type_13_Inch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   REEL 7&quot;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string String_FormMain_Cart_Reel_Type_7_Inch {
            get {
                return ResourceManager.GetString("String_FormMain_Cart_Reel_Type_7_Inch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ACCEPTED과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string String_FormMain_Communication_State_Accepted {
            get {
                return ResourceManager.GetString("String_FormMain_Communication_State_Accepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CONNECTED과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string String_FormMain_Communication_State_Connected {
            get {
                return ResourceManager.GetString("String_FormMain_Communication_State_Connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CONNECTING과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string String_FormMain_Communication_State_Connecting {
            get {
                return ResourceManager.GetString("String_FormMain_Communication_State_Connecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DISCONNECTED과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string String_FormMain_Communication_State_Disconnected {
            get {
                return ResourceManager.GetString("String_FormMain_Communication_State_Disconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   LISTEN과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string String_FormMain_Communication_State_Listen {
            get {
                return ResourceManager.GetString("String_FormMain_Communication_State_Listen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SOCK ERROR과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string String_FormMain_Communication_State_Socket_Error {
            get {
                return ResourceManager.GetString("String_FormMain_Communication_State_Socket_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Equal to (==)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string String_FormMain_Compare_Operator_EqualTo {
            get {
                return ResourceManager.GetString("String_FormMain_Compare_Operator_EqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Greater than (&gt;)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string String_FormMain_Compare_Operator_GreaterThan {
            get {
                return ResourceManager.GetString("String_FormMain_Compare_Operator_GreaterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Greater than or equal to (&gt;=)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string String_FormMain_Compare_Operator_GreaterThanOrEqualTo {
            get {
                return ResourceManager.GetString("String_FormMain_Compare_Operator_GreaterThanOrEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Less than (&lt;)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string String_FormMain_Compare_Operator_LessThan {
            get {
                return ResourceManager.GetString("String_FormMain_Compare_Operator_LessThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Less than or equal to (&lt;=)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string String_FormMain_Compare_Operator_LessThanOrEqualTo {
            get {
                return ResourceManager.GetString("String_FormMain_Compare_Operator_LessThanOrEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Not equal to (!=)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string String_FormMain_Compare_Operator_NotEqualTo {
            get {
                return ResourceManager.GetString("String_FormMain_Compare_Operator_NotEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please, wait for proper stop condition.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string String_FormMain_Exit_Condition_WaitForProperStop {
            get {
                return ResourceManager.GetString("String_FormMain_Exit_Condition_WaitForProperStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Completed cycle stop.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string String_FormMain_Information_Completed_CycleStop {
            get {
                return ResourceManager.GetString("String_FormMain_Information_Completed_CycleStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reset cycle stop by operator.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string String_FormMain_Information_Reset_CycleStop {
            get {
                return ResourceManager.GetString("String_FormMain_Information_Reset_CycleStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Set cycle stop by operator.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string String_FormMain_Information_Set_CycleStop {
            get {
                return ResourceManager.GetString("String_FormMain_Information_Set_CycleStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please, wait while finish to load a cart by MRBT.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string String_FormMain_Information_Wait_Mrbt_Load {
            get {
                return ResourceManager.GetString("String_FormMain_Information_Wait_Mrbt_Load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please, wait while finish to unload a cart by MRBT.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string String_FormMain_Information_Wait_Mrbt_Unload {
            get {
                return ResourceManager.GetString("String_FormMain_Information_Wait_Mrbt_Unload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ENTER USER ID과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string String_FormMain_labelLoginOperator {
            get {
                return ResourceManager.GetString("String_FormMain_labelLoginOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MRBT COM.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string String_FormMain_labelMobileRobotCommunication {
            get {
                return ResourceManager.GetString("String_FormMain_labelMobileRobotCommunication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   REEL TWR COM.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string String_FormMain_labelReelTowerCommunicationState {
            get {
                return ResourceManager.GetString("String_FormMain_labelReelTowerCommunicationState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ROBOT COM.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string String_FormMain_labelRobotCommunicationState {
            get {
                return ResourceManager.GetString("String_FormMain_labelRobotCommunicationState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Added a new account ({0}).과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string String_FormMain_Message_AddedANewAccount {
            get {
                return ResourceManager.GetString("String_FormMain_Message_AddedANewAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please, check reel tower to unload.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string String_FormMain_Message_CheckReelTowerToUnload {
            get {
                return ResourceManager.GetString("String_FormMain_Message_CheckReelTowerToUnload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please, choose proper assign reel count.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string String_FormMain_Message_ChoseProperAssignMaterialCount {
            get {
                return ResourceManager.GetString("String_FormMain_Message_ChoseProperAssignMaterialCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The manager account ({0}) is not available.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string String_FormMain_Message_ManagerAccountIsNotAvailable {
            get {
                return ResourceManager.GetString("String_FormMain_Message_ManagerAccountIsNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The reel ({0}) is not available.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string String_FormMain_Message_ReelIsNotAvailable {
            get {
                return ResourceManager.GetString("String_FormMain_Message_ReelIsNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please, remove failed the privde job ({0}).과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string String_FormMain_Message_RemoveFailedTheProvideJob {
            get {
                return ResourceManager.GetString("String_FormMain_Message_RemoveFailedTheProvideJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Remove the account ({0}).과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string String_FormMain_Message_RemoveTheAccount {
            get {
                return ResourceManager.GetString("String_FormMain_Message_RemoveTheAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please, select proper outport.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string String_FormMain_Message_SelectProperOutput {
            get {
                return ResourceManager.GetString("String_FormMain_Message_SelectProperOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The user account ({0}) is not available.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string String_FormMain_Message_UserAccountIsNotAvailable {
            get {
                return ResourceManager.GetString("String_FormMain_Message_UserAccountIsNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please, check vision process running.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string String_FormMain_Notification_Check_Vision_Run {
            get {
                return ResourceManager.GetString("String_FormMain_Notification_Check_Vision_Run", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please, dock a cart into work zone.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string String_FormMain_Notification_Dock_Cart {
            get {
                return ResourceManager.GetString("String_FormMain_Notification_Dock_Cart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to load configuration or model information from file!{0}Please, check the config file exist or version.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string String_FormMain_Notification_Load_Config_Failure {
            get {
                return ResourceManager.GetString("String_FormMain_Notification_Load_Config_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please, stop first to undock the cart.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string String_FormMain_Notification_Stop_To_Undock_Confirm {
            get {
                return ResourceManager.GetString("String_FormMain_Notification_Stop_To_Undock_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please, undock the cart from work zone.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string String_FormMain_Notification_Undock_Cart {
            get {
                return ResourceManager.GetString("String_FormMain_Notification_Undock_Cart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Would you like to undock the cart?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string String_FormMain_Notification_Undock_Confirm {
            get {
                return ResourceManager.GetString("String_FormMain_Notification_Undock_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The other vision process is running. Please, check vision process and restart.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string String_FormMain_Notification_Vision_Process_Launch_Failure {
            get {
                return ResourceManager.GetString("String_FormMain_Notification_Vision_Process_Launch_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vision process is not available.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string String_FormMain_Notification_Vision_Program_Exists {
            get {
                return ResourceManager.GetString("String_FormMain_Notification_Vision_Program_Exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Wait for reply reel unload move message...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string String_FormMain_Notification_WaitFor_Reply {
            get {
                return ResourceManager.GetString("String_FormMain_Notification_WaitFor_Reply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Would you like to remove the reels which are alredy assigned to unload then continue ?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string String_FormMain_Question_DuplicatedMaterialInformation {
            get {
                return ResourceManager.GetString("String_FormMain_Question_DuplicatedMaterialInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Would you like to exit the program ?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string String_FormMain_Question_Exit_Program {
            get {
                return ResourceManager.GetString("String_FormMain_Question_Exit_Program", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Detect the old reserved jobs.{0}Do you want to import it?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string String_FormMain_Question_ImportJob {
            get {
                return ResourceManager.GetString("String_FormMain_Question_ImportJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Provide job is not completed.{0}Do you want to pause the jobs ?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string String_FormMain_Question_ProvidJob_IsNot_Completed {
            get {
                return ResourceManager.GetString("String_FormMain_Question_ProvidJob_IsNot_Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Store operation is not completed.{0}Do you want to stop immediately ?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string String_FormMain_Question_StoreOperation_IsNot_Completed {
            get {
                return ResourceManager.GetString("String_FormMain_Question_StoreOperation_IsNot_Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MONITOR과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string String_FormMain_radioButtonJobMonitor {
            get {
                return ResourceManager.GetString("String_FormMain_radioButtonJobMonitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OPERATOR과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string String_FormMain_radioButtonLoginOperator {
            get {
                return ResourceManager.GetString("String_FormMain_radioButtonLoginOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SEARCH과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string String_FormMain_radioButtonSearchReel {
            get {
                return ResourceManager.GetString("String_FormMain_radioButtonSearchReel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   RETURN 13&quot;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string String_FormMain_Return_Reel_Type_13_Inch {
            get {
                return ResourceManager.GetString("String_FormMain_Return_Reel_Type_13_Inch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   RETURN 7&quot;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string String_FormMain_Return_Reel_Type_7_Inch {
            get {
                return ResourceManager.GetString("String_FormMain_Return_Reel_Type_7_Inch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   COMP LD과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string String_FormMain_Robot_Action_State_Completed_Load {
            get {
                return ResourceManager.GetString("String_FormMain_Robot_Action_State_Completed_Load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   COMP ULD과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string String_FormMain_Robot_Action_State_Completed_Unload {
            get {
                return ResourceManager.GetString("String_FormMain_Robot_Action_State_Completed_Unload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   LOAD과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string String_FormMain_Robot_Action_State_Do_Load {
            get {
                return ResourceManager.GetString("String_FormMain_Robot_Action_State_Do_Load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DO LD과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string String_FormMain_Robot_Action_State_Do_Loading {
            get {
                return ResourceManager.GetString("String_FormMain_Robot_Action_State_Do_Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   UNLOAD과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string String_FormMain_Robot_Action_State_Do_Unload {
            get {
                return ResourceManager.GetString("String_FormMain_Robot_Action_State_Do_Unload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DO ULD과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string String_FormMain_Robot_Action_State_Do_Unloading {
            get {
                return ResourceManager.GetString("String_FormMain_Robot_Action_State_Do_Unloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   FAILED과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string String_FormMain_Robot_Action_State_Failed {
            get {
                return ResourceManager.GetString("String_FormMain_Robot_Action_State_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   READY과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string String_FormMain_Robot_Action_State_Stopped {
            get {
                return ResourceManager.GetString("String_FormMain_Robot_Action_State_Stopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///    ACCOUNT 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string String_FormMain_tabPageAccount {
            get {
                return ResourceManager.GetString("String_FormMain_tabPageAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///     ALARM HISTORY  과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string String_FormMain_tabPageAlarmHistory {
            get {
                return ResourceManager.GetString("String_FormMain_tabPageAlarmHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///       CONFIG    과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string String_FormMain_tabPageConfig {
            get {
                return ResourceManager.GetString("String_FormMain_tabPageConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///        LOG    과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string String_FormMain_tabPageLog {
            get {
                return ResourceManager.GetString("String_FormMain_tabPageLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MAINTENANCE 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string String_FormMain_tabPageMaintenance {
            get {
                return ResourceManager.GetString("String_FormMain_tabPageMaintenance", resourceCulture);
            }
        }
        
        /// <summary>
        ///    OPERATION 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string String_FormMain_tabPageOperation {
            get {
                return ResourceManager.GetString("String_FormMain_tabPageOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///     PROVIDE JOB 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string String_FormMain_tabPageProvideJobLog {
            get {
                return ResourceManager.GetString("String_FormMain_tabPageProvideJobLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///    PROVIDE 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string String_FormMain_tabPageProvideOperation {
            get {
                return ResourceManager.GetString("String_FormMain_tabPageProvideOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///     REEL TOWER  과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string String_FormMain_tabPageReelTowerLog {
            get {
                return ResourceManager.GetString("String_FormMain_tabPageReelTowerLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///    MANAGER 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string String_FormMain_tabPageReelTowerManager {
            get {
                return ResourceManager.GetString("String_FormMain_tabPageReelTowerManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///     NOTIFIER  과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string String_FormMain_tabPageReelTowerNotifier {
            get {
                return ResourceManager.GetString("String_FormMain_tabPageReelTowerNotifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///       ROBOT    과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string String_FormMain_tabPageRobotLog {
            get {
                return ResourceManager.GetString("String_FormMain_tabPageRobotLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///      STORE   과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string String_FormMain_tabPageStoreOperation {
            get {
                return ResourceManager.GetString("String_FormMain_tabPageStoreOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///       VISION    과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string String_FormMain_tabPageVision {
            get {
                return ResourceManager.GetString("String_FormMain_tabPageVision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cleared remained unload requests in queue.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string String_FormQuedList_Notification_Cleared_Remained_Unload_Requests {
            get {
                return ResourceManager.GetString("String_FormQuedList_Notification_Cleared_Remained_Unload_Requests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Picking list is not available.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string String_FormQuedList_Notification_No_Picking_List {
            get {
                return ResourceManager.GetString("String_FormQuedList_Notification_No_Picking_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please, stop process first.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string String_FormQuedList_Notification_Stop_To_Show_Confirm {
            get {
                return ResourceManager.GetString("String_FormQuedList_Notification_Stop_To_Show_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   yyyy-MM-dd HH:mm:ss.fff과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string String_Generic_DateTime_Format {
            get {
                return ResourceManager.GetString("String_Generic_DateTime_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please, check system running environment.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string String_Information_Check_System_Running_Environment {
            get {
                return ResourceManager.GetString("String_Information_Check_System_Running_Environment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to create load request for ({0}).과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string String_Information_FailedToCreateLoadRequest {
            get {
                return ResourceManager.GetString("String_Information_FailedToCreateLoadRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please, initialize the system first.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string String_Information_Initialization_First {
            get {
                return ResourceManager.GetString("String_Information_Initialization_First", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please, load reel ({0}) on reel tower terminal과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string String_Information_LoadReelOnReelTowerTerminal {
            get {
                return ResourceManager.GetString("String_Information_LoadReelOnReelTowerTerminal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please, select proper material type information과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string String_Information_SelectProperMaterialInformation {
            get {
                return ResourceManager.GetString("String_Information_SelectProperMaterialInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please, stop process first.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string String_Information_Stop_Process_First {
            get {
                return ResourceManager.GetString("String_Information_Stop_Process_First", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please, take out the provided reel ({0}) on tower ({1}).과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string String_Information_TakeOutProvidedReel {
            get {
                return ResourceManager.GetString("String_Information_TakeOutProvidedReel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   INITIALIZING...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string String_Initializing {
            get {
                return ResourceManager.GetString("String_Initializing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   USER과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string String_Label_User {
            get {
                return ResourceManager.GetString("String_Label_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   LOGIN과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string String_Login {
            get {
                return ResourceManager.GetString("String_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   LOGOUT과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string String_Logout {
            get {
                return ResourceManager.GetString("String_Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MANUAL MODE과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string String_ManualMode {
            get {
                return ResourceManager.GetString("String_ManualMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MRBT AUTO과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string String_Mrbt_Auto_Mode {
            get {
                return ResourceManager.GetString("String_Mrbt_Auto_Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MRBT MANUAL과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string String_Mrbt_Manual_Mode {
            get {
                return ResourceManager.GetString("String_Mrbt_Manual_Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The work slot is empty. Change work slot.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string String_Notificatiion_Empty_Slot {
            get {
                return ResourceManager.GetString("String_Notificatiion_Empty_Slot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   NOTIFICATION과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string String_Notification {
            get {
                return ResourceManager.GetString("String_Notification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please, check robot state.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string String_Notification_Check_Robot_State {
            get {
                return ResourceManager.GetString("String_Notification_Check_Robot_State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please, check vision program path.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string String_Notification_Check_Vision_Program_Path {
            get {
                return ResourceManager.GetString("String_Notification_Check_Vision_Program_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please, check vision state. Must be stopped to live.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string String_Notification_Check_Vision_State_Stop_Live {
            get {
                return ResourceManager.GetString("String_Notification_Check_Vision_State_Stop_Live", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please, check reel storage program status with license then restart the program.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string String_Notification_CheckReelStorageProgramStatus {
            get {
                return ResourceManager.GetString("String_Notification_CheckReelStorageProgramStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Finished load reel from cart.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string String_Notification_Completed_Load_Reel_From_Cart {
            get {
                return ResourceManager.GetString("String_Notification_Completed_Load_Reel_From_Cart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to load a return reel.{0}It will be retried later by automatically.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string String_Notification_Failed_To_Load_Return {
            get {
                return ResourceManager.GetString("String_Notification_Failed_To_Load_Return", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please check the gripper and reel detect sensor. No reel in gripper과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string String_Notification_Gripper_State {
            get {
                return ResourceManager.GetString("String_Notification_Gripper_State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Refused load a reel process by tower.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string String_Notification_Refused_Load {
            get {
                return ResourceManager.GetString("String_Notification_Refused_Load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please, load a production cart.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string String_Notification_Required_Cart {
            get {
                return ResourceManager.GetString("String_Notification_Required_Cart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please, unload the completed production cart.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string String_Notification_Required_Unload_Cart {
            get {
                return ResourceManager.GetString("String_Notification_Required_Unload_Cart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please, rescan the qr code on reel.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string String_Notification_RescanTheQrCodeOnReel {
            get {
                return ResourceManager.GetString("String_Notification_RescanTheQrCodeOnReel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The return stage is empty.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string String_Notification_Return_Stage_Empty {
            get {
                return ResourceManager.GetString("String_Notification_Return_Stage_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Robot program state is not playing. Please, check safety sensors.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string String_Notification_Robot_Program_State {
            get {
                return ResourceManager.GetString("String_Notification_Robot_Program_State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OK과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string String_Ok {
            get {
                return ResourceManager.GetString("String_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DOCK과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string String_Process_Dock {
            get {
                return ResourceManager.GetString("String_Process_Dock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DONE과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string String_Process_Done {
            get {
                return ResourceManager.GetString("String_Process_Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   IDLE과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string String_Process_Idle {
            get {
                return ResourceManager.GetString("String_Process_Idle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DO LD과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string String_Process_Load {
            get {
                return ResourceManager.GetString("String_Process_Load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   READY과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string String_Process_Ready {
            get {
                return ResourceManager.GetString("String_Process_Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   LOADING과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string String_Process_State_Loading {
            get {
                return ResourceManager.GetString("String_Process_State_Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   UNLOADING과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string String_Process_State_Unloading {
            get {
                return ResourceManager.GetString("String_Process_State_Unloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   UNDOCK과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string String_Process_Undock {
            get {
                return ResourceManager.GetString("String_Process_Undock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DO ULD과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string String_Process_Unload {
            get {
                return ResourceManager.GetString("String_Process_Unload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   QUERY과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string String_Query {
            get {
                return ResourceManager.GetString("String_Query", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Would you like to reset the context of {0} stage ?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string String_Question_ClearMonitorStageContext {
            get {
                return ResourceManager.GetString("String_Question_ClearMonitorStageContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Decoded qr code is not recognized. Please, rescan the qr on reel.{0}({1})과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string String_Question_NotRecognizedQrCodeRetry {
            get {
                return ResourceManager.GetString("String_Question_NotRecognizedQrCodeRetry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The barcode of reel is not unique. Please, check the barcode.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string String_Reel_Barcode_Is_Not_Unique {
            get {
                return ResourceManager.GetString("String_Reel_Barcode_Is_Not_Unique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DETECTED과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string String_Reel_Detected {
            get {
                return ResourceManager.GetString("String_Reel_Detected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   REFRESH과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string String_Refresh {
            get {
                return ResourceManager.GetString("String_Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   REMOVE과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string String_Remove {
            get {
                return ResourceManager.GetString("String_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   REQUEST과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string String_Request {
            get {
                return ResourceManager.GetString("String_Request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SEARCH과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string String_Search {
            get {
                return ResourceManager.GetString("String_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   STOP과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string String_Stop {
            get {
                return ResourceManager.GetString("String_Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Load material operation timeout ({0}).과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string String_Warning_Reject_Message_LoadMaterialOperationTimeout {
            get {
                return ResourceManager.GetString("String_Warning_Reject_Message_LoadMaterialOperationTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Material information is not available.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string String_Warning_Reject_Message_MaterialInformationNotExist {
            get {
                return ResourceManager.GetString("String_Warning_Reject_Message_MaterialInformationNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Wrong tower state and material information is not available.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string String_Warning_Reject_Message_WrongMaterialInformation {
            get {
                return ResourceManager.GetString("String_Warning_Reject_Message_WrongMaterialInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please, release the cart in work area.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string String_Warning_Release_CartInWorkArea {
            get {
                return ResourceManager.GetString("String_Warning_Release_CartInWorkArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please, reset alarm state.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string String_Warning_Reset_Alarm {
            get {
                return ResourceManager.GetString("String_Warning_Reset_Alarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please, reset cycle stop state flag.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string String_Warning_Reset_Cycle_Stop {
            get {
                return ResourceManager.GetString("String_Warning_Reset_Cycle_Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap transfer_black {
            get {
                object obj = ResourceManager.GetObject("transfer_black", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap transfer_blue {
            get {
                object obj = ResourceManager.GetObject("transfer_blue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap transfer_green {
            get {
                object obj = ResourceManager.GetObject("transfer_green", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap transfer_red {
            get {
                object obj = ResourceManager.GetObject("transfer_red", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap transfer_white {
            get {
                object obj = ResourceManager.GetObject("transfer_white", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap transfer_yellow {
            get {
                object obj = ResourceManager.GetObject("transfer_yellow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
